# PLAY 01
- name: PLAY-01
  hosts: web
  tasks:
  - name: PLAY-01 TASK-01
    ansible.builtin.debug:
      msg: PLAY-01 TASK-01

# PLAY 02
- name: PLAY-02
  hosts: web
  tasks:
  - name: PLAY-02 TASK-01
    ansible.builtin.debug:
      msg: PLAY-02 TASK-01
