# Install nginx
- name: Install nginx and run
  host: web
  become: yes # take sudo access
  tasks:
  - name: install nginx
    ansible.builtin.package: #heterogeneous module will install all linux packages
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.package:
      name: nginx
      state: started
      enabled: yes