# variables
- name: variables
  hosts: web
  vars:
    COURSE: Devops with AWS
    DURATION: 120HRS
    TRAINER: Sivakumar M
  tasks:
    ansible.builtin.debug:
      msg: "Hi my name is {{TRAINER}}, I am teaching {{COURSE}} Duration will be {{DURATION}}"
  