# Getting vars from inventory
- name: variables Print
  hosts: web
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "I am learning {{COURSE}} duration is {{DURATION}}, and trainer is {{TRAINER}}"
    