- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: check process1
    ansible.builtin.shell: ps -ef | grep ssh 
    register: output
  
  - name: check the process2
    ansible.builtin.command: ps -ef | grep ssh
    register: output
    