- name: create ec2 and route53 records
  hosts: local
  connection: local

  vars:
    subnet_id: "subnet-0e6a016823adf702c" # place your subnet id subnet-0e6a016823adf702c
    sg_id: "sg-0bfc14741c51ad341" #sg-0bfc14741c51ad341
    ami_id: "ami-09c813fb71547fc4f" #ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
    zone: veeraprakash.online
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9
      
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: " {{ item }} "
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.veeraprakash.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: create r53 public record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #veeraprakash.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend" #when keyword should not have {{}}
